services:
  - type: web
    name: comicbook-api
    runtime: node
    branch: main
    plan: starter

    buildCommand: |
      npm install
      npx prisma generate
      npm run bundle:openapi

    preDeployCommand: |
      npx prisma migrate deploy
      # uncomment ONLY if you want to seed on every deploy
      npx prisma db seed

    startCommand: npm start

    
